export interface PersonalInfoElement {
  fullName: string;
  gender: number;
  email: string;
  dob: string;
  address: string;
  seats: number;
  motorType: string;
  favColor: string;
  hobbies: string;
}

export interface Dictionary {
  [key: string]: number;
}

//for demo purposes (charts display)
export const FORMINFO_STARTING_DATA = [
  {
    fullName: 'Sami',
    gender: 'male',
    email: 'email1@gmail.com',
    dob: 'Mon Jun 12 1989',
    address: 'Haifa',
    seats: 3,
    motorType: 'fuel',
    favColor: '#afafaf',
    hobbies: ['Swimming', 'Photography', 'Football'],
  },
  {
    fullName: 'Rani',
    gender: 'male',
    email: 'email2@gmail.com',
    dob: 'Mon Jun 12 1996',
    address: 'Tel Aviv',
    seats: 4,
    motorType: 'electric',
    favColor: '#afafaf',
    hobbies: ['Swimming', 'Reading', 'Hiking'],
  },
  {
    fullName: 'Fadi',
    gender: 'male',
    email: 'email3@gmail.com',
    dob: 'Mon Jun 12 1969',
    address: 'Nezareth',
    seats: 2,
    motorType: 'fuel',
    favColor: '#afafaf',
    hobbies: ['Hiking', 'Camping', 'Photography'],
  },
  {
    fullName: 'Haya',
    gender: 'female',
    email: 'email4@gmail.com',
    dob: 'Mon Jun 12 1979',
    address: 'Beer Sheva',
    seats: 4,
    motorType: 'electric',
    favColor: '#afafaf',
    hobbies: ['Reading', 'Photography'],
  },
  {
    fullName: 'Ruba',
    gender: 'female',
    email: 'email5@gmail.com',
    dob: 'Mon Jun 12 1999',
    address: 'Haifa',
    seats: 3,
    motorType: 'fuel',
    favColor: '#afafaf',
    hobbies: ['Reading', 'Hiking'],
  },
  {
    fullName: 'Sewar',
    gender: 'female',
    email: 'email6@gmail.com',
    dob: 'Mon Jun 12 1959',
    address: 'Tel Aviv',
    seats: 3,
    motorType: 'electric',
    favColor: '#afafaf',
    hobbies: ['Swimming', 'Photography', 'Reading'],
  },
  {
    fullName: 'Jaber',
    gender: 'male',
    email: 'email7@gmail.com',
    dob: 'Mon Jun 12 1966',
    address: 'Haifa',
    seats: 2,
    motorType: 'fuel',
    favColor: '#afafaf',
    hobbies: ['Football', 'Camping'],
  },
  {
    fullName: 'Rafat',
    gender: 'male',
    email: 'email8@gmail.com',
    dob: 'Mon Jun 12 1988',
    address: 'Haifa',
    seats: 4,
    motorType: 'fuel',
    favColor: '#afafaf',
    hobbies: ['Photography', 'Hiking'],
  },
  {
    fullName: 'Fidaa',
    gender: 'female',
    email: 'email9@gmail.com',
    dob: 'Mon Jun 12 1979',
    address: 'Haifa',
    seats: 3,
    motorType: 'electric',
    favColor: '#afafaf',
    hobbies: ['Swimming', 'Photography'],
  },
  {
    fullName: 'Hamed',
    gender: 'male',
    email: 'email10@gmail.com',
    dob: 'Mon Jun 12 1958',
    address: 'Nezareth',
    seats: 3,
    motorType: 'fuel',
    favColor: '#afafaf',
    hobbies: ['Reading'],
  },
  {
    fullName: 'Faten',
    gender: 'female',
    email: 'email11@gmail.com',
    dob: 'Mon Jun 12 1976',
    address: 'Nezareth',
    seats: 3,
    motorType: 'electric',
    favColor: '#afafaf',
    hobbies: ['Hiking', 'Football'],
  },
  {
    fullName: 'Shaker',
    gender: 'male',
    email: 'email12@gmail.com',
    dob: 'Mon Jun 12 1998',
    address: 'Haifa',
    seats: 3,
    motorType: 'fuel',
    favColor: '#afafaf',
    hobbies: ['Hiking', 'Camping', 'Photography'],
  },
  {
    fullName: 'Fadya',
    gender: 'female',
    email: 'email13@gmail.com',
    dob: 'Mon Jun 12 1974',
    address: 'Haifa',
    seats: 3,
    motorType: 'electric',
    favColor: '#afafaf',
    hobbies: ['Football', 'Camping', 'Swimming'],
  },
  {
    fullName: 'Abla',
    gender: 'female',
    email: 'email14@gmail.com',
    dob: 'Mon Jun 12 2001',
    address: 'Tel Aviv',
    seats: 3,
    motorType: 'fuel',
    favColor: '#afafaf',
    hobbies: ['Swimming', 'Reading'],
  },
  {
    fullName: 'Shadi',
    gender: 'male',
    email: 'email15@gmail.com',
    dob: 'Mon Jun 12 1994',
    address: 'Nezareth',
    seats: 3,
    motorType: 'electric',
    favColor: '#afafaf',
    hobbies: ['Football', 'Camping'],
  },
  {
    fullName: 'Rami',
    gender: 'male',
    email: 'email16@gmail.com',
    dob: 'Mon Jun 12 1985',
    address: 'Tel Aviv',
    seats: 3,
    motorType: 'electric',
    favColor: '#afafaf',
    hobbies: ['Swimming', 'Football'],
  },
];
